/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithNavbarIndexRouteImport } from './routes/_withNavbar/index'
import { Route as WithNavbarMlRouteImport } from './routes/_withNavbar/ml'
import { Route as WithNavbarListRouteImport } from './routes/_withNavbar/list'
import { Route as WithNavbarLayoutRouteImport } from './routes/_withNavbar/layout'
import { Route as AuthLIndexRouteImport } from './routes/_auth/L/index'

const WithNavbarIndexRoute = WithNavbarIndexRouteImport.update({
  id: '/_withNavbar/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavbarMlRoute = WithNavbarMlRouteImport.update({
  id: '/_withNavbar/ml',
  path: '/ml',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavbarListRoute = WithNavbarListRouteImport.update({
  id: '/_withNavbar/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavbarLayoutRoute = WithNavbarLayoutRouteImport.update({
  id: '/_withNavbar/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLIndexRoute = AuthLIndexRouteImport.update({
  id: '/_auth/L/',
  path: '/L/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/layout': typeof WithNavbarLayoutRoute
  '/list': typeof WithNavbarListRoute
  '/ml': typeof WithNavbarMlRoute
  '/': typeof WithNavbarIndexRoute
  '/L': typeof AuthLIndexRoute
}
export interface FileRoutesByTo {
  '/layout': typeof WithNavbarLayoutRoute
  '/list': typeof WithNavbarListRoute
  '/ml': typeof WithNavbarMlRoute
  '/': typeof WithNavbarIndexRoute
  '/L': typeof AuthLIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_withNavbar/layout': typeof WithNavbarLayoutRoute
  '/_withNavbar/list': typeof WithNavbarListRoute
  '/_withNavbar/ml': typeof WithNavbarMlRoute
  '/_withNavbar/': typeof WithNavbarIndexRoute
  '/_auth/L/': typeof AuthLIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/layout' | '/list' | '/ml' | '/' | '/L'
  fileRoutesByTo: FileRoutesByTo
  to: '/layout' | '/list' | '/ml' | '/' | '/L'
  id:
    | '__root__'
    | '/_withNavbar/layout'
    | '/_withNavbar/list'
    | '/_withNavbar/ml'
    | '/_withNavbar/'
    | '/_auth/L/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithNavbarLayoutRoute: typeof WithNavbarLayoutRoute
  WithNavbarListRoute: typeof WithNavbarListRoute
  WithNavbarMlRoute: typeof WithNavbarMlRoute
  WithNavbarIndexRoute: typeof WithNavbarIndexRoute
  AuthLIndexRoute: typeof AuthLIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withNavbar/': {
      id: '/_withNavbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithNavbarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withNavbar/ml': {
      id: '/_withNavbar/ml'
      path: '/ml'
      fullPath: '/ml'
      preLoaderRoute: typeof WithNavbarMlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withNavbar/list': {
      id: '/_withNavbar/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof WithNavbarListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withNavbar/layout': {
      id: '/_withNavbar/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof WithNavbarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/L/': {
      id: '/_auth/L/'
      path: '/L'
      fullPath: '/L'
      preLoaderRoute: typeof AuthLIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WithNavbarLayoutRoute: WithNavbarLayoutRoute,
  WithNavbarListRoute: WithNavbarListRoute,
  WithNavbarMlRoute: WithNavbarMlRoute,
  WithNavbarIndexRoute: WithNavbarIndexRoute,
  AuthLIndexRoute: AuthLIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
